### ISSUE TITLE
Include partial sass file in component does not update web browser in watch

### ISSUE THREAD

**Issue by stevenbriscoeca** [ionic-team/stencil-sass#29] opened 2020-03-30 20:17 UTC
Hello,

If you have this structure : 
```
--src
   |---components
            |---breadcrumb
                      |---breadcrumb.scss
                      |---_partial.scss
```

In breadcrumb.scss I include partial.scss.

When I change the css file partial.scss and save that file, I expect the visuals in the browser to have updated.

I need to save breadcrumb.scss to take into account the partials update

**Comment by dutscher** [comment] 2020-06-16 11:45
+1

**Comment by TrimA74** [comment] 2020-10-28 14:58
same as  #8 .. still waiting for a fix

**Comment by splitinfinities** [comment] 2021-09-24 21:33
We do have a prominent ticket in the @stencil/core backlog for this. I'll keep my eye on it and report back here. The challenge is the watched files that get prepared when the Stencil compiler starts up can't get a map of all included files- even within css files BTW.

**Comment by jared-christensen** [comment] 2023-06-22 13:36
This seems to be working today and I think this can be closed. I can import a SCSS file in my component SCSS file and make changes to the imported file and the change is reflected in the browser.

**Comment by rwaskiewicz** [comment] 2023-06-30 13:55
I believe this issue has been resolved. Using `@stencil/sass@3.0.4`, I'm unable to reproduce this with the provided reproduction case. I recorded quick video of my repro, where I could see changes to a partials file getting picked up:


https://github.com/ionic-team/stencil-sass/assets/1930213/337df0d0-c8dd-49f5-aa07-9b7b3dffcc10

In that video, I have a component, `my-component` that imports `style.scss` via `styleUrl` in the Component decorator. `style.scss` uses my partial file to provide color to `h1` tags. When I open my partial file, update `primary-color` and save, the change are reflected in my browser.

As a result, I'm going to close this issue. Should this reappear, please feel free to open a new issue. Thank you!

**Closed by rwaskiewicz** 2023-06-30 13:55 UTC
Labels: Bug: Validated
