### ISSUE TITLE
watch mode for global styles not working

### ISSUE THREAD

**Issue by x1c0** [ionic-team/stencil-sass#15] opened 2019-02-21 14:50 UTC
I use shared styles across components, and for organisation purposes I have several sass files like so:

/src/global/app.scss
/src/global/header.scss
/src/global/footer.scss

Then inside of app.scss I link to the other sass files like so:
`@import "header.scss"`

This works great on first render, but when changing one of this imported styles, despite seeing the console debug message from stencil that styles were generated, they are not applied on the page, not even with hard reload.

Is this not possible?

**Comment by pr3tori4n** [comment] 2019-06-04 18:37
I'm seeing this as well. Any file referenced from the injectGlobalPaths array is not recompiled on-save. for example:
`plugins:[
    sass({
      injectGlobalPaths: ['src/globalStyles/variables.scss']
    })
  ] `

This is true if your change is valid or invalid. You have to restart the stencil dev server, at which point these files are re-compiled, at which point you may get errors (so you're getting a lot of false positives your changes don't break the build - which would be rather bad if doing any refactoring).

**Comment by flobacher** [comment] 2019-08-08 22:27
@x1c0 we used globalStyle and face the same issue... 
Our workaround was to put all styles into this one global file, but to be able to use imports would be really  nice!

Variables are in a file referenced via injectGlobalPath..
We import it at the top of the global styles. Changeing anything in this varisble file triggeres a rebuild but does not regenerate global stxles 😔

**Comment by flobacher** [comment] 2019-08-26 07:45
@manucorporat any update on this?

**Comment by 4aficiona2** [comment] 2019-10-02 13:41
Did somebody find a workaround for this or has a solution so live reload works during development?

I almost can't believe how you should be able to develop a component library without having hot reload working. This seems so crucial for a consistent UI / UX and a proper DX.

**Comment by jan-paulus** [comment] 2019-12-02 16:37
We're using [concurrently](https://www.npmjs.com/package/concurrently) to run the stencil dev-server, node-sass and postcss-cli at the same time. In addition to this we set the `reloadStrategy` of the stencil dev-server to `pageReload` (see docs [here](https://stenciljs.com/docs/dev-server)).

The process looks as follows:

- node-sass watches for scss file changes and compiles them to a temporary (gitignored) directory
- postcss watches for changes in this temporary directory and compiles the css files to the dist directory
- stencil dev-server picks up this file change and reloads the page

This is just a workaround and we're hoping to see an actual option in the future.

**Comment by jkarttunen** [comment] 2020-03-24 20:21
Seconded, this is very annoying, since I get Jest errors or something else completely unrelated on every typo on variable name, but delayed until I edit some component file. 
My best workaround was to import the root variables & mixins file in each component.

**Comment by break-stuff** [comment] 2020-03-24 20:48
*** if you are using StoryBook ***

I have been wrestling with this for some time. While I don't have a direct solution to this issue, what I did find is that I can leverage StoryBook to hot-reload my SASS changes. I still wire up my SASS for Stencil to compile with my builds, but my development is done in StoryBook stories, so I leverage it's WebPack implementation to watch for my changes and reload my stories with the updated styles. Here is an example project where you can see my setup:

https://github.com/break-stuff/cwg-design-system

**Comment by jkarttunen** [comment] 2020-03-25 18:44
My workaround is to go old-school and
1. Use node-sass to compile every .scss file to .css files with `node-sass -w src/ -o src/ --recursive` (eg. button.scss to button.css)
2. import button.css to stencil. Now css changes trigger stencil to refresh.
3. For this to work, i need to import design tokens on every component `@import '../_tokens';`

**Comment by patrickalima98** [comment] 2020-08-16 14:40
Hello, any news?

**Comment by jaredcbaum** [comment] 2020-08-25 02:48
duplicate of #8

**Closed by jaredcbaum** 2020-08-25 02:48 UTC

**Comment by Mo-Mongi** [comment] 2022-08-24 14:58
best way is to use an outsource desktop app for this. I use an app called **Koala**  it's free and it's working just fine.
